import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { PageHeader } from "@/components/features/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { db } from "@/lib/db";
import { requireMember } from "@/server/tenant";

export const metadata: Metadata = { title: "Report" };

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const member = await requireMember();
  const { id } = await params;

  // Scoped by agency: a report id alone must not expose another agency's numbers.
  const report = await db.report.findFirst({
    where: { id, client: { agencyId: member.agencyId } },
    include: { client: { select: { name: true } } },
  });

  if (!report) notFound();

  return (
    <>
      <PageHeader
        title={report.client.name}
        description={`${report.periodStart.toLocaleDateString("en-IN")} – ${report.periodEnd.toLocaleDateString("en-IN")}`}
        action={
          <div className="flex gap-2">
            {report.emailedAt && <Badge variant="secondary">Emailed</Badge>}
            {report.whatsappAt && <Badge variant="secondary">WhatsApp</Badge>}
          </div>
        }
      />

      {report.deliveryError && (
        <Card className="border-destructive/50 bg-destructive/5 mb-4">
          <CardContent className="py-4 text-sm text-pretty">
            {report.deliveryError}
          </CardContent>
        </Card>
      )}

      <Card>
        <CardContent className="p-4">
          {/*
            The stored HTML is generated by us in server/reports.ts, and every value
            interpolated into it is escaped there. It is not user-submitted markup.
          */}
          <div dangerouslySetInnerHTML={{ __html: report.html }} />
        </CardContent>
      </Card>
    </>
  );
}
